main: fr.lyneris.narutouhc.NarutoUHC
version: 2.0.1
author: Rhodless
name: NarutoUHC
depend:
  - Lyneris-UHC
commands:
  ns:
    description: Naruto command
  boost:
    description: Hokage boost command
  reveal:
    description: Reveal hokage command